server:
  port: 8081

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
  db:
    secret: ${DB_CRYPTO_SECRET}
  auth:
    secret: ${AUTH_JWT_SECRET}
    expiration: 3600

spring:

  application:
    name: bankcards

  datasource:
    url: ${BANK_CARD_DB_URL:jdbc:postgresql://localhost:5432/bank_card_db?currentSchema=bank_card_schema}
    username: ${BANK_CARD_DB_USERNAME:bank_card_user}
    password: ${BANK_CARDS_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: bank_card_schema

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml
    enabled: true
    contexts: dev
    default-schema: bank_card_schema
    liquibase-schema: bank_card_schema

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
