server:
  port: 8081

spring:

  application:
    name: bankcards

  datasource:
    url: ${BANK_CARD_DB_URL}
    username: ${BANK_CARD_DB_USERNAME}
    password: ${BANK_CARDS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: bankcards

  liquibase:
    enabled: true
    contexts: dev
    default-schema: bankcards
    liquibase-schema: bankcards

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
